"""Portable GPU player, embedding the canonical glyph atlas and lossless cells."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parent.parent
def document(data):
    source=(ROOT/'dist/ascii-display.js').read_text();start=source.index('export class AsciiDisplay');end=source.index('\nexport function animationDocument',start);definition=source[start:end].replace('export class','class',1)
    atlas=(ROOT/'dist/data/glyph-atlas-v45.json').read_text();encoded=json.dumps(data,separators=(',',':')).replace('<','\\u003c')
    bootstrap="""const d=DATA,font=FONT,canvas=document.querySelector('#art'),display=new AsciiDisplay(canvas,font),slider=document.querySelector('#time');let raw=d.cells?Uint8Array.from(atob(d.cells),c=>c.charCodeAt(0)):null;const n=d.grid[0]*d.grid[1],total=d.frame_count||d.frames.length;if(d.encoding==='interleaved-xor-u8')for(let f=1;f<total;f++)for(let i=0;i<n*2;i++)raw[f*n*2+i]^=raw[(f-1)*n*2+i];slider.min=0;slider.max=total-1;let frame=0,playing=true,last=0;function draw(){let text,gray;if(raw){text='';gray=new Uint8Array(n);for(let i=0;i<n;i++){text+=String.fromCharCode(raw[(frame*n+i)*2]);gray[i]=raw[(frame*n+i)*2+1];}}else{text=d.frames[frame];gray=d.luminance[frame];}display.draw(text,gray,d.grid,d.presentation?.[0]||600);slider.value=frame;document.querySelector('#counter').textContent=(frame+1)+' / '+total;}document.querySelector('#play').onclick=()=>{playing=!playing;document.querySelector('#play').textContent=playing?'Pause':'Play';};slider.oninput=()=>{frame=+slider.value;playing=false;draw();};function tick(t){if(playing&&t-last>=1000/d.fps){frame=(frame+1)%total;last=t;draw();}requestAnimationFrame(tick);}draw();requestAnimationFrame(tick);""".replace('DATA',encoded,1).replace('FONT',atlas,1)
    return '<!doctype html><meta charset="utf-8"><title>NULL GENESIS V4.5</title><style>body{background:#050505;color:#ccc;text-align:center;font:14px Consolas,monospace}canvas{display:block;margin:20px auto;max-width:95vw;max-height:85vh}button,input{margin:10px;background:#111;color:#ccc;border:1px solid #555}</style><canvas id="art"></canvas><div><button id="play">Pause</button><input id="time" type="range"><span id="counter"></span></div><script>'+definition+';'+bootstrap+'</script>'
