"""Create the versioned UI while keeping the V3 app module available."""
from pathlib import Path
root=Path(__file__).resolve().parent.parent
p=root/'dist/app-v3.js';text=p.read_text(encoding='utf-8')
text=text.replace("from './store.js'","from './store-v45.js'")
text="import {AsciiDisplay,animationDocument} from './ascii-display.js';\nlet asciiFont,asciiPlayer;\n"+text
text="import {readJson} from './engine.js';\n"+text
text=text.replace("const v3=$('engine-version').value==='3.0.0'","const v3=$('engine-version').value!=='1.0.0'")
text=text.replace("g.genome_version!=='web-3.0.0'","!['web-3.0.0','web-4.5.0'].includes(g.genome_version)")
text=text.replace("?'V3 animated synthesis'", "?(studio.release==='v45'?'V4.5 animated synthesis':'V3 animated synthesis')")
text=text.replace("$('engine-version').value='3.0.0'","$('engine-version').value=g.genome_version==='web-4.5.0'?'4.5.0':'3.0.0'")
text=text.replace("version:'3.0.0',rarity:$('rarity').value","version:$('engine-version').value,framing:$('framing-mode').value,rarity:$('rarity').value")
text=text.replace("studio.release==='v3'", "studio.release!=='legacy'")
text=text.replace("studio.release!=='v3'", "studio.release==='legacy'")
text=text.replace("'/v3/collection/", "'/'+studio.release+'/collection/")
text=text.replace("'/v3/reports/", "'/'+studio.release+'/reports/")
text=text.replace("registry=cfg.v3Registry||studio.v3Registry;recipes=cfg.v3Recipes||studio.v3Recipes;", "registry=cfg.registry45;recipes=cfg.recipes45;")
text=text.replace("$('backend-label').textContent=studio.engine.backend+' / V3'", "$('backend-label').textContent=studio.engine.backend+' / V4.5'")
text=text.replace("$('release-picker').querySelector('[value=\"v3\"]').disabled=!studio.v3Audit?.passed;", "$('release-picker').querySelector('[value=\"v3\"]').disabled=!studio.v3Audit?.passed;$('release-picker').querySelector('[value=\"v45\"]').disabled=!(studio.audit45?.passed&&studio.audit45?.visual_review_approved);")
text=text.replace("if(studio.release!=='legacy')packet(await studio.api('/api/item?edition=1'),1);", "if(studio.release!=='legacy')packet(await studio.api('/api/item?edition=1'),1);")
# Replace only the actual draw function, preserving archived draw routines.
start=text.index('\nfunction draw(){')+1;end=text.index('\nfunction analytics()',start)
text=text[:start]+'''function draw(){const canvas=$('animation-canvas'),[w,h]=current?gridOf(current):[80,80],square=current?.genome?.genome_version==='web-4.5.0';canvas.width=square?600:w*13;canvas.height=square?600:h*24;const ctx=canvas.getContext('2d');ctx.fillStyle='#050505';ctx.fillRect(0,0,canvas.width,canvas.height);if(!current)return;const chars=(anim?anim.frames[frame]:current.ascii).replaceAll('\\n',''),levels=anim?anim.luminance[frame]:current.luminance,cw=canvas.width/w,ch=canvas.height/h;ctx.font=ch+'px Consolas,monospace';ctx.textBaseline='top';for(let i=0;i<w*h;i++){const v=Math.round(levels[i]);ctx.fillStyle=`rgb(${v},${v},${v})`;ctx.fillText(chars[i],i%w*cw+(square?cw*.22:0),Math.floor(i/w)*ch);}if($('show-grid').checked){ctx.strokeStyle='#ffffff16';ctx.lineWidth=.5;for(let x=0;x<=w;x++){ctx.beginPath();ctx.moveTo(x*cw,0);ctx.lineTo(x*cw,canvas.height);ctx.stroke();}for(let y=0;y<=h;y++){ctx.beginPath();ctx.moveTo(0,y*ch);ctx.lineTo(canvas.width,y*ch);ctx.stroke();}}$('timeline').value=frame;$('frame-label').textContent=frame+' / '+(anim?anim.frames.length-1:0);$('timeline-seconds').textContent=(frame/(anim?.fps||12)).toFixed(2)+' SEC';}
''' +text[end:]
text=text.replace("function draw(){const canvas=$('animation-canvas')", "function draw(){if(current?.genome?.genome_version==='web-4.5.0'&&asciiFont){let canvas=$('animation-canvas');if(!canvas.dataset.gpu){const next=canvas.cloneNode(false);next.dataset.gpu='true';canvas.replaceWith(next);canvas=next;asciiPlayer=new AsciiDisplay(canvas,asciiFont);}asciiPlayer.draw(anim?anim.frames[frame]:current.ascii,anim?anim.luminance[frame]:current.luminance,gridOf(current),600,$('show-grid').checked);$('timeline').value=frame;$('frame-label').textContent=frame+' / '+(anim?anim.frames.length-1:0);$('timeline-seconds').textContent=(frame/(anim?.fps||12)).toFixed(2)+' SEC';return;}if($('animation-canvas').dataset.gpu){const old=$('animation-canvas'),next=old.cloneNode(false);delete next.dataset.gpu;asciiPlayer?.dispose();old.replaceWith(next);}const canvas=$('animation-canvas')")
text=text.replace("studio=await new Studio().init();", "asciiFont=await AsciiDisplay.font();studio=await new Studio().init();")
start=text.index('function experiments(){');end=text.index('\nasync function exportItems(',start)
text=text[:start]+'''function experiments(){const rows=studio.experiments45.items||[],report=studio.report45,q=$('experiment-search').value.toLowerCase();summaries('experiment-summary',[['CANDIDATES',rows.length],['NATIVE GRIDS','30 / 50 / 64 / 80 / 96 / 120'],['CANONICAL RELEASE',report?.canonical_grid?.join(' × ')||'Under review'],['VALIDATION',report?.passed?'200 full CUDA timelines passed':'Experimental']]);$('experiment-grid-view').innerHTML=rows.filter(m=>JSON.stringify(m).toLowerCase().includes(q)).map(m=>'<article class="collection-card"><img loading="lazy" src="'+esc($('experiment-grid').value?'/v45/experiments/'+m.id+'-'+$('experiment-grid').value+'.png':m.preview)+'" alt="'+esc(m.id)+'"><div class="card-title"><span>'+esc(m.id)+'</span><span>'+esc(m.rarity)+'</span></div><small>'+esc(m.framing)+'<br>FILL '+(100*m.quality.dimension_occupancy).toFixed(1)+'% · QUALITY '+m.quality.quality_score+'</small><div class="card-actions"><button data-experiment="'+m.id+'">Inspect ↗</button><button data-compare="'+m.id+'">Compare grids</button></div></article>').join('');document.querySelectorAll('[data-experiment]').forEach(b=>b.onclick=()=>task(async()=>{packet(await studio.experiment45(b.dataset.experiment));show('lab');}));document.querySelectorAll('[data-compare]').forEach(b=>b.onclick=()=>task(()=>compareExperiment(b.dataset.compare)));}
async function compareExperiment(id){const views=studio.report45.comparisons.filter(c=>c.id===id);$('experiment-compare').hidden=false;$('experiment-compare').innerHTML=views.map(v=>'<article class="panel"><h2>Native '+v.grid+' × '+v.grid+'</h2><img src="/v45/experiments/'+id+'-'+v.grid+'.png" alt="Native grid comparison"><p>QUALITY '+v.quality.quality_score+' · '+v.gpu_ms+' MS CUDA</p></article>').join('');$('experiment-compare').scrollIntoView({behavior:'smooth'});}
''' +text[end:]
text=text.replace("if(!m||!c)throw Error('The measured grid comparison is unavailable.');", "if(!m||!c)throw Error('The measured grid comparison is unavailable.');")
text=text.replace("c.width=w*13;c.height=h*24;", "c.width=a.presentation?600:w*13;c.height=a.presentation?600:h*24;")
text=text.replace("function animationHTML(a){const payload=", "function animationHTML(a){if(current?.genome?.genome_version==='web-4.5.0')return animationDocument(a,asciiFont);const payload=")
text=text.replace('animationDocument(a,asciiFont)',"animationDocument({...a,presentation:[Number($('presentation-size').value),Number($('presentation-size').value)]},asciiFont)")
text=text.replace("gridOf(current),600,$('show-grid').checked", "gridOf(current),Number($('presentation-size').value),$('show-grid').checked")
text=text.replace("$('download-png').onclick=()=>current&&task(async()=>{const r=await fetch(current.preview);", "$('download-png').onclick=()=>current&&task(async()=>{if(current.genome.genome_version==='web-4.5.0'){const c=document.createElement('canvas'),display=new AsciiDisplay(c,asciiFont);display.draw(current.ascii,current.luminance,gridOf(current),Number($('presentation-size').value));const r=await fetch(c.toDataURL('image/png'));save(await r.blob(),'null-genesis.png','image/png');display.dispose();return;}const r=await fetch(current.preview);")
text=text.replace("x.font=\"24px Consolas,monospace\"", "x.font=(c.height/h)+\"px Consolas,monospace\"")
# The original portable player has a fixed 30-cell grid and no local `h`.
text=text.replace('x.fillRect(0,0,390,720);x.font=(c.height/h)+"px Consolas,monospace"', 'x.fillRect(0,0,390,720);x.font="24px Consolas,monospace"')
text=text.replace("i%w*13,Math.floor(i/w)*24", "i%w*(c.width/w)+(a.presentation?c.width/w*.22:0),Math.floor(i/w)*(c.height/h)")
# Native grid changes must also restore category pools for V3 generation.
text=text.replace("$('engine-version').onchange=versionControls;", "$('engine-version').onchange=()=>{const v=$('engine-version').value;options('native-grid',(v==='4.5.0'?[30,50,64,80,96,120]:[30,50]).map(n=>[String(n),n+' × '+n]),v==='4.5.0'?'80':'50');for(const c of CATEGORIES)options('cat-'+c,[['','Deterministic synthesis'],...registry.traits.filter(t=>t.category===c&&(v==='4.5.0'||t.id.startsWith('V3.'))).map(t=>[t.id,t.label])]);versionControls();};")
text=text.replace("$('engine-version').value=g.genome_version==='web-4.5.0'?'4.5.0':'3.0.0';versionControls();for", "$('engine-version').value=g.genome_version==='web-4.5.0'?'4.5.0':'3.0.0';$('engine-version').onchange();$('framing-mode').value=g.composition?.mode||'Tight Portrait';for")
text=text.replace("rows.length+' EDITIONS / '+(studio.release!=='legacy'?'V3':'ORIGINAL')", "rows.length+' EDITIONS / '+(studio.release==='v45'?'V4.5':studio.release==='v3'?'V3':'ORIGINAL')")
text=text.replace("g.algorithm==='AES-256-GCM'?{envelope:g}:{genome:g}", "g.algorithm==='AES-256-GCM'?{envelope:g}:{genome:g.genome||g}")
text=text.replace("'NATIVE GRIDS','30 × 30 / 50 × 50'", "'NATIVE GRIDS','30 / 50 / 64 / 80 / 96 / 120'")
text=text.replace("$('experiment-grid-view').innerHTML=rows.filter", "$('grid-benchmark').innerHTML='<table><thead><tr><th>Native grid</th><th>GPU ms / still</th><th>Quality proxy</th><th>Visible primitives</th></tr></thead><tbody>'+(report?.grids||[]).map(r=>'<tr><td>'+r.grid+' × '+r.grid+'</td><td>'+r.median_gpu_ms.toFixed(2)+'</td><td>'+r.mean_quality.toFixed(2)+'</td><td>'+r.mean_visible_objects.toFixed(1)+'</td></tr>').join('')+'</tbody></table>';$('experiment-grid-view').innerHTML=rows.filter")
text=text.replace("$('lab-grid').textContent=grid.join(' × ');", "$('lab-grid').textContent=grid.join(' × ')+(p.quality?.dimension_occupancy?' · '+(100*p.quality.dimension_occupancy).toFixed(1)+'% fill':'');")
text=text.replace("$('lab-art').src=p.preview;", "$('lab-art').closest('.lab-preview').classList.toggle('square-presentation',p.genome?.genome_version==='web-4.5.0'||p.metadata?.genome_version==='web-4.5.0');$('lab-art').src=p.preview;")
text=text.replace("$('hero-art').src=p.preview;", "$('hero-art').parentElement.classList.toggle('square-presentation',p.genome?.genome_version==='web-4.5.0'||p.metadata?.genome_version==='web-4.5.0');$('hero-art').closest('.featured').classList.toggle('square-presentation',p.genome?.genome_version==='web-4.5.0'||p.metadata?.genome_version==='web-4.5.0');$('hero-art').src=p.preview;")
text=text.replace('V3 editions · deterministic animation in every rarity','Animated editions · deterministic motion in every rarity')
text=text.replace("$('migrate-dna').disabled=g.genome_version==='web-3.0.0'", "$('migrate-dna').disabled=g.genome_version==='web-4.5.0'")
text=text.replace("files.push([dir+'preview.png',new Uint8Array(await r.arrayBuffer())]);", "files.push([dir+'preview.png',new Uint8Array(await r.arrayBuffer())]);if(studio.release==='v45'){const q=await readJson(metadata(p).quality_record),data=await readJson(metadata(p).media.frames);files.push([dir+'quality.json',JSON.stringify(q)],[dir+'animation.frames.json',JSON.stringify(data)],[dir+'animation.html',animationDocument(data,asciiFont)]);}")
text=text.replace("[dir+'animation.html',animationDocument(data,asciiFont)]);}", "[dir+'animation.html',animationDocument(data,asciiFont)]);for(const ext of ['mp4','webm']){const url=metadata(p).media[ext];if(url){const video=await fetch(url);if(!video.ok)throw Error('Legendary video export failed.');files.push([dir+'animation.'+ext,new Uint8Array(await video.arrayBuffer())]);}}}")
text=text.replace('function chart(id,data){let sum=Object.values(data).reduce((a,b)=>a+b,0);', 'function chart(id,data,reference=null){let sum=reference??Object.values(data).reduce((a,b)=>a+b,0),scale=reference===null?sum:Math.max(1,...Object.values(data));')
text=text.replace("style=\"width:'+100*n/Math.max(sum,1)+'%", "style=\"width:'+100*n/Math.max(scale,1)+'%")
text=text.replace('.slice(0,10)));chart', '.slice(0,10)),rows.length);chart')
text=text.replace('m.base_concepts||[m.family]', 'm.source_concepts||m.base_concepts||[m.family]')
(root/'dist/app-v45.js').write_text(text,encoding='utf-8')
import subprocess
html=subprocess.run(['C:/Program Files/Git/cmd/git.exe','-c','safe.directory='+root.as_posix(),'show','05ce4b9b338414086198083eaf768ee5ebb69353:dist/index.html'],cwd=root,capture_output=True,check=True).stdout.decode('utf-8');html=html.replace('src="/app-v3.js"','src="/app-v45.js?v=4.5.0"').replace('<option value="v3">V3 collection</option>','<option value="v45">V4.5 collection</option><option value="v3">V3 collection</option>').replace('<option value="3.0.0">V3 · Procedural trait fusion</option>','<option value="4.5.0">V4.5 · Silhouette fusion</option><option value="3.0.0">V3 · Procedural trait fusion</option>')
marker='<select id="native-grid"';start=html.index(marker);end=html.index('</select>',start);html=html[:start]+'<select id="native-grid" name="native-grid">'+''.join(f'<option value="{n}"'+(' selected' if n==80 else '')+f'>{n} × {n}</option>' for n in (30,50,64,80,96,120))+html[end:]
html=html.replace('<div id="v3-controls">','<div id="v3-controls"><label>Framing mode<select id="framing-mode">'+''.join(f'<option>{n}</option>' for n in ('Tight Portrait','Head-and-Torso','Half-Body','Full-Body','Wide Creature','Vertical Relic','Mask/Icon','Distributed Abstract'))+'</select></label>')
html=html.replace('PTFE / V3','PTFE / V4.5').replace('30 / 50 ASCII','80 × 80 ASCII').replace('530 curated','742 curated').replace('1,200','2,400').replace('120 experiments','200 experiments')
html=html.replace('ENGINE 3.0.0 · 900 / 2,500 CELLS','ENGINE 4.5.0 · 900–14,400 CELLS').replace('<strong>530</strong>','<strong>742</strong>').replace('300 concepts · 120 modifiers · 110 NFT values','300 concepts · 120 modifiers · 322 NFT values').replace('530 CURATED VALUES','742 CURATED VALUES')
html=html.replace('Migrate to V3','Migrate to V4.5')
html=html.replace('style.css?v=3.0.0-final','style.css?v=4.5.0-final')
html=html.replace('app-v45.js?v=4.5.0"','app-v45.js?v=4.5.0-final"')
html=html.replace('Create V3 descendant','Create V4.5 descendant').replace('native 30×30 and 50×50 deterministic grayscale organisms','six native grids and deterministic grayscale organisms').replace('Matched 30×30 and 50×50 native geometry. Measured NVIDIA render results.','Two hundred matched CUDA timelines, old/new artwork and six native grid comparisons.').replace('href="/v3/reports/experiments.json"','href="/v45/reports/experiments.json"')
html=html.replace('V3 editions animate in every rarity.','V4.5 and V3 editions animate in every rarity.')
html=html.replace('<label>ASCII scale','<label>Presentation export<select id="presentation-size"><option value="300">300 × 300</option><option value="600" selected>600 × 600</option><option value="1200">1200 × 1200</option></select></label><label>ASCII scale')
html=html.replace('<div id="experiment-grid-view"','<section id="grid-benchmark" class="panel"></section><div id="experiment-grid-view"')
html=html.replace('<option value="">Both resolutions</option><option value="30">30 × 30</option><option value="50">50 × 50</option>','<option value="">All six native grids</option>'+''.join(f'<option value="{n}">{n} × {n}</option>' for n in (30,50,64,80,96,120)))
(root/'dist/index.html').write_text(html,encoding='utf-8')
# Versioned square standalone player retains V3 decoder and media links.
viewer=(root/'dist/v3/viewer.js').read_text(encoding='utf-8').replace("'/v3/", "'/v45/").replace("from '../", "from '../")
viewer=viewer.replace("a.grid[0]*13",'600').replace("a.grid[1]*24",'600').replace("ctx.font='24px Consolas,monospace'","ctx.font=(600/w)+'px Consolas,monospace'").replace('i%w*13,Math.floor(i/w)*24','i%w*(600/w)+600/w*.22,Math.floor(i/w)*(600/w)')
viewer="import {AsciiDisplay} from '../ascii-display.js';\nlet display;\n"+viewer
start=viewer.index('function draw(){');end=viewer.index('\nfunction tick',start);viewer=viewer[:start]+"function draw(){display.draw(a.frames[frame],a.luminance[frame],a.grid,600);$('timeline').value=frame;$('counter').textContent=`${frame+1} / ${a.frames.length}`;}"+viewer[end:]
viewer=viewer.replace("a=decodeAnimation(await readJson(path));", "a=decodeAnimation(await readJson(path));display=new AsciiDisplay($('art'),await AsciiDisplay.font());")
(root/'dist/v45/viewer.js').write_text(viewer,encoding='utf-8');(root/'dist/v45/viewer.html').write_text((root/'dist/v3/viewer.html').read_text(encoding='utf-8'),encoding='utf-8')
print('V4.5 studio controls and square viewer created')
