import {readFileSync,existsSync} from 'node:fs';
import {join} from 'node:path';
import {gunzipSync} from 'node:zlib';
import {createHash} from 'node:crypto';
import assert from 'node:assert/strict';
import {checkZip} from './validate-v3.mjs';
import {checkGenome} from '../dist/engine.js';
const CATEGORIES=['Back','Body','Eyewear','Features','Form','Headwear','Mask','Method','Motion','Palette','Stage'];
const QUOTAS={COMMON:1900,UNCOMMON:900,RARE:400,EPIC:110,LEGENDARY:23},FRAMES={COMMON:36,UNCOMMON:48,RARE:72,EPIC:96,LEGENDARY:144};
const REQUIRED=['ascii.txt','preview.png','metadata.json','genome.dna.json','quality.json','animation.frames.json.gz','animation.html'];
const hash=b=>createHash('sha256').update(b).digest('hex');
export async function validateV45(root){
 const raw=p=>readFileSync(join(root,p)),json=p=>JSON.parse(raw(p)),packed=p=>JSON.parse(gunzipSync(raw(p)));
 const release=json('v45/collection/release.json'),audit=json('v45/reports/collection-audit.json'),experiments=json('v45/reports/experiments.json'),visual=json('v45/reports/production-visual-review.json'),compat=json('v45/reports/compatibility.json'),registry=json('data/traits-v45.json'),recipes=json('data/recipes-v45.json'),catalog=json('v45/collection/catalog.json');
 assert(release.complete&&audit.passed&&audit.visual_review_approved&&visual.passed&&compat.passed,'Incomplete V4.5 release gates');assert(experiments.passed&&experiments.visual_review_approved&&experiments.full_timelines);assert.equal(experiments.experiment_count,200);assert.deepEqual(release.canonical_grid,[80,80]);assert.deepEqual(release.presentation,[600,600]);assert.equal(audit.animated,3333);assert.equal(audit.owner_keys_public,false);assert.equal(audit.hardware.backend,'CUDA');assert.equal(registry.traits.length,742);assert.equal(recipes.recipes.length,2400);assert.equal(catalog.length,3333);
 for(const [file,expected] of Object.entries(visual.images))assert.equal(hash(raw('v45/reports/'+file)),expected,'Reviewed production image changed');
 const expression=json('v45/reports/trait-expression.json');assert(expression.passed&&expression.operative_new_values===212);assert.equal(new Set(recipes.recipes.map(r=>JSON.stringify([r.source_concept_ids,r.operator,r.level,r.trait_ids]))).size,2400,'Alias composite programs');
 const density=json('v45/reports/density-compatibility.json');assert(density.passed);assert.equal(density.candidate_fingerprints_compared,3333);assert.equal(density.default_changes,0);assert.equal(density.operative_controls.length,6);
 const crypto=json('v45/reports/crypto-interop.json');assert(crypto.passed&&crypto.native_to_studio&&crypto.studio_to_native&&crypto.studio_wrong_key_rejected);assert.equal(crypto.native_tamper_cases_rejected,5);assert.equal(crypto.studio_tamper_cases_rejected,5);
 const videos=json('v45/reports/video-validation.json');assert(videos.passed);assert.equal(videos.legendary_editions,23);assert.equal(videos.decoded_videos,46);assert.equal(videos.decoded_frames,6624);
 const definitions=new Map(registry.traits.map(t=>[t.id,t])),recipeIDs=new Set(recipes.recipes.map(r=>r.id)),rarities={},hashes=new Set(),fingerprints=new Set(),ranks=new Set(),profiles=new Set(),sources=new Set(),usedRecipes=new Set(),attributes=new Set(),expectedExports=new Map();let editions=0,frames=0,encrypted=0;
 const nonces=new Set();
 for(let block=0;block<34;block++)for(const row of packed('v45/collection/block-'+String(block).padStart(2,'0')+'.json.gz')){
  editions++;const m=row.metadata,expected=catalog[editions-1],id=String(editions).padStart(4,'0'),prefix='v45/collection/',n=80*80;
  assert.equal(row.edition,editions);assert.deepEqual(expected,m,'Catalog/block metadata mismatch');assert.deepEqual(m.native_grid,[80,80]);assert.deepEqual(m.presentation_size,[600,600]);assert.equal(m.genome_version,'web-4.5.0');assert.equal(m.canonical_renderer,'cuda-sdf-4.5.0');const lines=row.ascii.split('\n');assert.equal(lines.pop(),'');assert.equal(lines.length,80);assert(lines.every(r=>r.length===80&&/^[\x20-\x7e]*$/.test(r)));assert.equal(hash(row.ascii),m.canonical_hash);assert(!hashes.has(m.canonical_hash)&&!fingerprints.has(m.genome_fingerprint),'Duplicate canonical');hashes.add(m.canonical_hash);fingerprints.add(m.genome_fingerprint);
  assert.equal(row.luminance.length,n);assert(row.luminance.every(x=>Number.isFinite(x)&&x>=0&&x<=255));assert.deepEqual(m.attributes.map(a=>a.trait_type),CATEGORIES);for(const a of m.attributes){const d=definitions.get(a.id);assert(d&&d.category===a.trait_type&&d.label===a.value,'Invalid curated attribute');attributes.add(a.id);}for(const id of m.source_concepts){assert(definitions.has(id),'Unknown source');sources.add(id);}for(const id of m.composite_traits){assert(recipeIDs.has(id),'Unknown composite');usedRecipes.add(id);}assert(m.quality.accepted);assert(m.frame_occupancy>=.69&&m.frame_occupancy<=.87);assert(Object.keys(m.quality.checks).length===10);assert(m.loop_validation.periodic&&m.loop_validation.animated);assert(m.uniqueness.unique);assert(Number.isInteger(m.rank)&&m.rank>=1&&m.rank<=3333&&!ranks.has(m.rank));ranks.add(m.rank);rarities[m.rarity]=(rarities[m.rarity]||0)+1;
  const preview=raw(prefix+'previews/'+id+'.png');assert.equal(preview.subarray(0,8).toString('hex'),'89504e470d0a1a0a');assert.equal(preview.readUInt32BE(16),600);assert.equal(preview.readUInt32BE(20),600);
  const frameBytes=raw(prefix+'animations/'+id+'.frames.json.gz'),a=JSON.parse(gunzipSync(frameBytes)),cells=Buffer.from(a.cells,'base64');assert(['interleaved-u8','interleaved-xor-u8'].includes(a.encoding));assert.deepEqual(a.grid,[80,80]);assert.equal(a.genome_fingerprint,m.genome_fingerprint);assert.equal(a.fps,m.animation.fps);assert.equal(a.seconds,m.animation.seconds);assert.equal(a.frame_count,FRAMES[m.rarity]);assert.equal(a.frame_count,a.fps*a.seconds);assert.equal(cells.length,a.frame_count*n*2);
  if(a.encoding==='interleaved-xor-u8')for(let f=1;f<a.frame_count;f++)for(let i=0;i<n*2;i++)cells[f*n*2+i]^=cells[(f-1)*n*2+i];let first='',moving=false;for(let i=0;i<n;i++){first+=String.fromCharCode(cells[i*2]);if((i+1)%80===0)first+='\n';}assert.equal(first,row.ascii);for(let i=0;i<cells.length;i+=2){assert(cells[i]>=32&&cells[i]<=126);if(i>=n*2&&(cells[i]!==cells[i%(n*2)]||cells[i+1]!==cells[(i+1)%(n*2)]))moving=true;}assert(moving,'Static animation');frames+=a.frame_count;
  const qualityBytes=raw(prefix+'quality/'+id+'.json'),q=JSON.parse(qualityBytes);assert.equal(q.genome_fingerprint,m.genome_fingerprint);assert.deepEqual(q.metrics,m.quality);assert.deepEqual(q.loop,m.loop_validation);
  if(row.dna.algorithm){encrypted++;assert.equal(row.dna.version,45);assert.equal(row.dna.algorithm,'AES-256-GCM');assert.equal(row.dna.fingerprint,m.genome_fingerprint);assert.equal(Buffer.from(row.dna.nonce,'base64').length,12);assert.equal(Buffer.from(row.dna.aad,'base64').toString(),'NULL-GENESIS/web-genome/v45/'+m.genome_fingerprint);assert(!row.genome&&!row.scene&&!row.config&&!row.dna.key&&!row.dna.genome);}else{await checkGenome(row.genome);await checkGenome(row.dna);assert.equal(row.dna.fingerprint,m.genome_fingerprint);}
  if(row.dna.algorithm){assert(!nonces.has(row.dna.nonce),'Repeated owner-key AES nonce');nonces.add(row.dna.nonce);}
  const ex=new Map([['ascii.txt',hash(row.ascii)],['metadata.json',hash(JSON.stringify(m))],['genome.dna.json',hash(JSON.stringify(row.dna))],['quality.json',hash(qualityBytes)],['preview.png',hash(preview)],['animation.frames.json.gz',hash(frameBytes)]]);
  if(m.rarity==='LEGENDARY'){profiles.add(m.animation.profile);for(const ext of ['mp4','webm']){const path=prefix+'animations/'+id+'.'+ext;assert(existsSync(join(root,path)));assert.equal(m.media[ext],'/'+path);ex.set('animation.'+ext,hash(raw(path)));}}
  expectedExports.set(editions,ex);
 }
 assert.equal(editions,3333);assert.equal(frames,audit.frames);assert.deepEqual(rarities,QUOTAS);assert.equal(ranks.size,3333);assert.equal(sources.size,300);assert(usedRecipes.size>=2000);assert.deepEqual([...profiles].sort((a,b)=>a-b),Array.from({length:23},(_,i)=>i));
 const manifest=json('v45/collection/exports/index.json'),inventory=new Map();assert.equal(manifest.owner_keys_included,false);assert.equal(manifest.count,3333);let zipEntries=0;
 for(const part of manifest.parts){const bytes=raw(part.url.slice(1));assert.equal(bytes.length,part.bytes);assert(bytes.length<25*1048576);assert.equal(hash(bytes),part.sha256);zipEntries+=checkZip(bytes,inventory,REQUIRED,(edition,file,plain)=>{const expected=expectedExports.get(edition).get(file);if(expected)assert.equal(hash(['metadata.json','genome.dna.json'].includes(file)?JSON.stringify(JSON.parse(plain)):plain),expected,'Archive/source mismatch: '+edition+'/'+file);else if(file==='animation.html')assert(plain.toString().includes('class AsciiDisplay')&&plain.toString().includes('NULL GENESIS V4.5'));else assert.fail('Unexpected archive payload');});}
 assert.equal(inventory.size,3333);for(const m of catalog){const files=inventory.get(m.edition);for(const f of REQUIRED)assert(files.has(f));if(m.rarity==='LEGENDARY')for(const ext of ['mp4','webm'])assert(files.has('animation.'+ext));}
 return {passed:true,version:'4.5.0',editions,frames,encrypted,curated_values:742,recipes:2400,recipes_used:usedRecipes.size,source_concepts:sources.size,category_values_used:attributes.size,native_grid:[80,80],presentation:[600,600],archive_parts:manifest.parts.length,zip_entries_crc_verified:zipEntries,archive_source_hashes_verified:true};
}
